linters:
 enable:
    - bodyclose
    - asasalint
    - bidichk
    - containedctx
    - cyclop
    - unused
    - dogsled
    # - dupl
    - durationcheck
    - errchkjson
    - errname
    - errorlint
   #  - goconst