# docker-compose.yml
version: '3.8'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    command: make run
    volumes: # Add this section
      - ./backend:/app # Replace with your Go app's path in the container
    depends_on:
      - db
      - redis
    restart: always

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot
    restart: always

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stories
    ports:
      - 5431:5432
    restart: always
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email mark.corray.off@gmail.com -d stories.mark-anikin.com --agree-tos
    restart: always

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
